import Foundation

struct GearData {
    static let gear: [[String: String]] = [
        ["name": "Arrow", "weight": "No size"],
        ["name": "Bandage", "weight": "No size"],
        ["name": "Blessed/Cursed water", "weight": "Minor"],
        ["name": "Bolt", "weight": "No size"],
        ["name": "Boot", "weight": "Minor"],
        ["name": "Bottle (wine or beer)", "weight": "Minor"],
        ["name": "Carpeting tool", "weight": "Minor"],
        ["name": "Checker (game)", "weight": "No size"],
        ["name": "Climbing gear", "weight": "Regular"],
        ["name": "Cloth (standard)", "weight": "Minor"],
        ["name": "Cloth (fine)", "weight": "Minor"],
        ["name": "Compass", "weight": "No size"],
        ["name": "Cult token (fine)", "weight": "No size"],
        ["name": "Cult token (simple)", "weight": "No size"],
        ["name": "Dice (bone)", "weight": "No size"],
        ["name": "Dog", "weight": "Heavy"],
        ["name": "Flatboat", "weight": "Heavy"],
        ["name": "Grapnel", "weight": "Regular"],
        ["name": "Hatchet", "weight": "Minor"],
        ["name": "Knapsack", "weight": "Minor"],
        ["name": "Lab (portable)", "weight": "Heavy"],
        ["name": "Lamp", "weight": "Minor"],
        ["name": "Lamp oil", "weight": "Minor"],
        ["name": "Lockpick", "weight": "No size"],
        ["name": "Makeup", "weight": "No size"],
        ["name": "Map (regular area)", "weight": "No size"],
        ["name": "Match", "weight": "No size"],
        ["name": "Mirror (glass)", "weight": "Minor"],
        ["name": "Parchment tube", "weight": "Minor"],
        ["name": "Perfume", "weight": "Minor"],
        ["name": "Prybar", "weight": "Minor"],
        ["name": "Quiver", "weight": "Minor"],
        ["name": "Ration (day)", "weight": "Minor"],
        ["name": "Rope, elven", "weight": "Minor"],
        ["name": "Rope, regular", "weight": "Regular"],
        ["name": "Sack", "weight": "Minor"],
        ["name": "Scroll (blank)", "weight": "No size"],
        ["name": "Shevvak", "weight": "Regular"],
        ["name": "Skiing gear", "weight": "Regular"],
        ["name": "Sled", "weight": "Heavy"],
        ["name": "Sleeping bag", "weight": "Regular"],
        ["name": "Snare", "weight": "Minor"],
        ["name": "Snow Monkey", "weight": "Heavy"],
        ["name": "Spell book (blank)", "weight": "Regular"],
        ["name": "Stick (long)", "weight": "Regular"],
        ["name": "Tent", "weight": "Heavy"],
        ["name": "Tinderbox", "weight": "Minor"],
        ["name": "Torch", "weight": "Minor"],
        ["name": "Warm coat", "weight": "Regular"],
        ["name": "Water container", "weight": "Minor"],
        ["name": "Zoruk (battle)", "weight": "Heavy"],
        ["name": "Zoruk (riding)", "weight": "Heavy"]
    ]
}
